# Generated by Django 4.1.7 on 2023-04-27 00:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("carts", "0002_cart_message"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cart",
            name="message",
        ),
    ]
